esphome:
  name: wand-regler

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NZWpkmabuD/G5Y8eSKUpUUxxhtL2Y2MVp245f2Zi2Ds="

ota:
  password: "40a510df1858bbe5dfe2ed2b8336fed5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wand-Regler Fallback Hotspot"
    password: "6ycBCLMSg7ht"

captive_portal:
    
# Example configuration entry
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12 # nicht benutzt da das Display keine Daten schickt
  
font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: fontRoboto
    size: 20

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO16
    temperature:
      id: "temperatureSensor"
      name: "Living Room Temperature"
    humidity:
      id: "humiditySensor"
      name: "Living Room Humidity"
    update_interval: 60s

# Diese Switches sollen die Soll Temparatur erhöhen oder erniedrigen
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Increase temperature"
    filters:
      - delayed_off: 10ms
    
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Decrease temperature"
    filters:
      - delayed_off: 10ms

climate:
  - platform: bang_bang
    name: "Wand Tremometer Gumbo"
    sensor: temperatureSensor
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C

    away_config:
      default_target_temperature_low: 12 °C
      default_target_temperature_high: 16 °C

    heat_action:
      - homeassistant.service:
          service: esphome.input_boolean.heizkreis_1.turn_on
    idle_action:
      - homeassistant.service:
          service: esphome.input_boolean.heizkreis_1.turn_off
 

display:
  - platform: st7735
    model: "INITR_BLACKTAB"
    reset_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO2 #A0
    rotation: 90
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 5s
    lambda: |-
      it.printf(0, 0, id(fontRoboto), "Temp: %.1f", id(temperatureSensor).state);
      it.printf(0, 30, id(fontRoboto), "Humid: %.1f", id(humiditySensor).state);

