esphome:
  name: heizverteiler-randa

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "g3cxQtTgvwE05Bl7c63c35mPQOvcR/KJ86X845dgWyA="

ota:
  password: "dbce4dfae0dfdb046133cfd994256d0f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heizverteiler Fallback Hotspot"
    password: "UapfElEsElJO"

captive_portal:

switch:
  - platform: gpio
    name: "Control 1"
    inverted: true
    pin: 5
  - platform: gpio
    name: "Control 2"
    inverted: true
    pin: 4
  - platform: gpio
    name: "Control 3"
    inverted: true
    pin: 14
  - platform: gpio
    name: "Control 4"
    inverted: true
    pin: 12
  - platform: gpio
    name: "Control 5"
    inverted: true
    pin: 13
  - platform: gpio
    name: "Control 6"
    inverted: true
    pin: 16

dallas:
  - pin: 2
    update_interval: 60s

sensor:
  - platform: dallas
    address: 0x223c01d607b92828
    name: "Ventil 1"
  - platform: dallas
    address: 0xf63c01d6070bfc28
    name: "Ventil 2"
